### PR TITLE
8.md - Change first screenshot and link

### PR DESCRIPTION
**Pull request by lmalhoit**
Change first screenshot to reflect proper sandbox link and change link below in first step

https://user-images.githubusercontent.com/4925801/34446352-45ecc14c-eca8-11e7-86b3-c70c180322f2.png

@annegentle

### CODE REVIEW

**Comment by annegentle** [comment]
Do you want to change screenshots also? The PR only contains `.md` files.

**Comment by lmalhoit** [comment]
I don't know where they're supposed to reside. I'm happy to do it if you tell me the directory and I imagine I need access.

**Comment by lmalhoit** [comment]
Okay, this is now all of the screenshots that needed to be changed.

**Comment by lmalhoit** [comment]
@annegentle All of the screenshots should be right now. But, there is a conflict with postman1. However, it's grayed out for me, so I probably don't have the rights to fix it. It should look like this:
postman1

**Comment by annegentle** [comment]
Okay, this is great work @lmalhoit! I'll resolve the pull request.

**Comment by annegentle** [comment]
Yeah! Next I'll make a release and push to staging. I'll send a link for you to review on staging.

**Pull request merged**
